version: '3.8'
services:
  db_userService:
    image: postgres:15
    container_name: db_userService
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: social_network
      POSTGRES_PASSWORD: SocialMedia2025
    ports:
      - "5432:5432"

  db_postService:
    image: postgres:15
    container_name: db_postService
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: post_service
      POSTGRES_PASSWORD: PostService2025
    ports:
      - "5433:5432"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/cp-server:7.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  # Kafka topic initialization
  kafka-setup:
    image: confluentinc/cp-server:7.2.1
    container_name: kafka-setup
    depends_on:
      - kafka
    command: >
      bash -c "
        echo Waiting for Kafka to be ready...
        cub kafka-ready -b kafka:9092 1 40
        echo Creating Kafka topics...
        kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic user_registered
        kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic post_viewed
        kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic post_liked
        kafka-topics --create --if-not-exists --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 --topic post_comment
        echo Kafka topics created.
      "
  user-service:
    build: ./UserService
    container_name: user_service
    depends_on:
      - db_userService
      - kafka-setup
    environment:
      DBNAME: social_network
      USER: user
      PASSWORD: SocialMedia2025
      HOST: db_userService
      SECRET_KEY: gV64m9aIzFG4qpgVphvQbPQrtAO0nM-7YwwOvu0XPt5KJOjAy4AfgLkqJXYEt
      ALGORITHM: HS256
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8002:8002"

  post-service:
    build: ./PostService
    container_name: post_service
    depends_on:
      - db_postService
      - kafka-setup
    environment:
      DBNAME1: post_service
      USER1: admin
      PASSWORD1: PostService2025
      HOST1: db_postService
      PORT1: "5432"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "50051:50051"

  api-gateway:
    build: ./APIGateway
    container_name: api_gateway
    depends_on:
      - user-service
      - post-service
      # - kafka
    environment:
      USER_SERVICE: http://user-service:8002/app/v1/users/
      POST_SERVICE: post-service:50051
    ports:
      - "8080:8080"

  